### ISSUE TITLE
mypy runs in both pre-commit ci and github actions

### ISSUE THREAD

**Issue by SiQube** [aeye-lab/pymovements#573]
we check mypy with both github actions and pre-commit-ci. maybe we can discuss dropping one (my vote is for github actions).

**Comment by dkrako** [comment]
my certain vote is to remove both flake8, mypy and pylint completely from pre-commit-ci

**Comment by dkrako** [comment]
actually I would even opt for removing mypy and pylint from pre-commit completely. they are much too slow, commit times of above 5seconds are totally unacceptable for me and thus pre-commit is currently not very usable as an installed git hook (otherwise one have to type --no-verify everytime on commit). flake8 can stay as it's fast enough.

but maybe there's a way to run these only on pull requests and not for commits.

**Comment by SiQube** [comment]
you can uninstall pre-commit locally

**Comment by dkrako** [comment]
I mean, technically you're correct, there's no need to run pre-commit locally, but you seem to assume that everyone should share your workflow, which is not the case.

in case I want to fix a raised error in a pre-commit hook, this means I would have to commit and push my changes, wait until pre-commit-bot finishes, click on the pre-commit workflow on github and then look at the error message.

the obvious workflow with a lot less friction and wasted time is just running pre-commit locally.

You already have removed the possibility to run pre-commit locally in tox with #564 (which I now see could have been a mistake to approve, but there's no problem reverting that in the future if necessary), so having it installed is currently the most intuitive way of local usage.

**Comment by dkrako** [comment]
I have changed my mind, see #587
